### ISSUE TITLE
Facebook auth breaks everything

### ISSUE THREAD

**Issue by uncledent** [vipy-me/vipy-server#1]
After facebook login attempt auth not working any more:

_body: "{"status":"Internal Server Error","error":"nats:   @#timeout"
url:"https://api.vipy.me/auth"

user service is also broken, 'Access-Control-Allow-Origin' error

**Comment by konstantinwirz** [comment]
A request without body to /auth endpoint has provoked that error.

**Comment by konstantinwirz** [comment]
#73bbe40ba28d31dcae20d2d1a6ab51bfa01290c0 fix this
